name: MoreHealth
main: MoreHealth\Loader
version: 2.0.0-BETA
api: 3.0.0-ALPHA10
author: VMPE Development Team

permissions:
    morehealth:
        default: op
        description: ""
        children:
            morehealth.setdefault:
                default: op
                description: ""
            morehealth.set:
                default: op
                description: ""
                children:
                    morehealth.set.other:
                        default: op
                        description: ""
            morehealth.restoredefault:
                default: op
                description: ""
            morehealth.restore:
                default: op
                description: ""
                children:
                    morehealth.restore.other:
                        default: op
                        description: ""
