name: MoreHealth
main: MoreHealth\Loader
version: 2.0.0-BETA
api: 3.0.0-ALPHA10
author: VMPE Development Team
website: https://github.com/iksaku/MoreHealth

permissions:
    morehealth:
        default: op
        description: "Change player's max health"
        children:
            morehealth.setdefault:
                default: op
                description: "Modify the default health limit in MoreHealth.yml"
            morehealth.set:
                default: op
                description: "Change the health limit"
                children:
                    morehealth.set.other:
                        default: op
                        description: "Change another player's health"
            morehealth.restoredefault:
                default: op
                description: "Restore the default health limit to 20 in MoreHealth.yml"
            morehealth.restore:
                default: op
                description: "Restore the health limit to the default specified in MoreHealth.yml"
                children:
                    morehealth.restore.other:
                        default: op
                        description: "Restore another player's health"
