name: MoreHealth
main: MoreHealth\Loader
version: 1.0.2
api: 1.0.0
author: iksaku
website: https://github.com/iksaku/MoreHealth

permissions:
    morehealth:
        default: op
        description: "Change player's max health"
        children:
            morehealth.setdefault:
                default: op
                description: "Modify the default health limit in MoreHealth.yml"
            morehealth.set:
                default: op
                description: "Change the health limit"
                children:
                    morehealth.set.use:
                        default: op
                        description: "Change your health"
                    morehealth.set.other:
                        default: op
                        description: "Change another player's health"
            morehealth.restoredefault:
                default: op
                description: "Restore the default health limit to 20 in MoreHealth.yml"
            morehealth.restore:
                default: op
                description: "Restore the health limit to the default specified in MoreHealth.yml"
                children:
                    morehealth.restore.use:
                        default: op
                        description: "Restore your health"
                    morehealth.restore.other:
                        default: op
                        description: "Restore another player's health"